// // src/dashboard/AdminDashboard/ManagePayments/ManagePayments.tsx
// import React, { useEffect, useState } from 'react';
// import { useAppSelector, useAppDispatch } from '../../../app/store';
// import { setLoading, setPayments, setError, createPayment } from '../../../features/payments/paymentSlice';
// import { FaEdit } from 'react-icons/fa';
// import { FaTrash } from 'react-icons/fa';
// import './ManagePayments.css';

// // Define PublicUser interface based on auth.service.ts
// interface PublicUser {
//   user_id: number;
//   email: string | null;
//   name: string;
//   role: "user" | "admin" | null;
// }

// // Define Payment interface
// interface Payment {
//   payment_id: number;
//   user_id: number;
//   booking_id: number;
//   amount: number;
//   status: string;
//   created_at: string;
// }

// const ManagePayments = () => {
//   const { payments, loading, error } = useAppSelector((state) => state.payments);
//   const dispatch = useAppDispatch();
//   const { token, user } = useAppSelector((state) => state.user) as { token: string | null; user: PublicUser | null };
//   const role = user?.role;
//   const userId = user?.user_id;

//   const [creating, setCreating] = useState(false);
//   const [newPayment, setNewPayment] = useState({
//     booking_id: '',
//     amount: '',
//     status: 'pending', // Default status
//   });

//   useEffect(() => {
//     const fetchPayments = async () => {
//       if (!userId || !token) return;
//       dispatch(setLoading());
//       try {
//         const url = role === 'admin' ? 'http://localhost:8081/payments' : `http://localhost:8081/payments?userId=${userId}`;
//         const response = await fetch(url, {
//           headers: { Authorization: `Bearer ${token}` },
//         });
//         if (!response.ok) {
//           throw new Error('Failed to fetch payments');
//         }
//         const result = await response.json();
//         dispatch(setPayments(result));
//       } catch (err: unknown) {
//         let message = 'Network error occurred';
//         if (err instanceof Error) {
//           message = err.message;
//         }
//         dispatch(setError(message));
//       }
//     };
//     fetchPayments();
//   }, [dispatch, token, role, userId]);

//   const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
//     const { name, value } = e.target;
//     setNewPayment((prev) => ({
//       ...prev,
//       [name]: value,
//     }));
//   };

//   const handleCreate = async () => {
//     if (!userId) return;
//     const payload = {
//       booking_id: parseInt(newPayment.booking_id, 10),
//       amount: parseFloat(newPayment.amount),
//       status: newPayment.status,
//     };
//     dispatch(setLoading());
//     try {
//       const response = await fetch('http://localhost:8081/payments', {
//         method: 'POST',
//         headers: {
//           'Content-Type': 'application/json',
//           Authorization: `Bearer ${token}`,
//         },
//         body: JSON.stringify(payload),
//       });
//       if (!response.ok) throw new Error('Create failed');
//       const result = await response.json();
//       dispatch(createPayment(result));
//       setCreating(false);
//       setNewPayment({
//         booking_id: '',
//         amount: '',
//         status: 'pending',
//       });
//     } catch (err: unknown) {
//       let message = 'Network error occurred';
//       if (err instanceof Error) {
//         message = err.message;
//       }
//       dispatch(setError(message));
//     }
//   };

//   const handleCancel = () => {
//     setCreating(false);
//     setNewPayment({
//       booking_id: '',
//       amount: '',
//       status: 'pending',
//     });
//   };

//   if (loading) return <div className="loading">Loading...</div>;
//   if (error) return <div className="error-message">{error}</div>;

//   return (
//     <div className="manage-payments">
//       <h2 className="payments-title">Manage Payments</h2>
//       <button className="create-btn" onClick={() => setCreating(true)}>Create Payment</button>
//       <table className="payments-table">
//         <thead>
//           <tr>
//             <th>Payment ID</th>
//             <th>Booking ID</th>
//             <th>Amount</th>
//             <th>Status</th>
//             <th>Created At</th>
//           </tr>
//         </thead>
//         <tbody>
//           {creating && (
//             <tr className="payment-row">
//               <td></td> {/* Payment ID auto-generated by backend */}
//               <td><input type="number" name="booking_id" value={newPayment.booking_id} onChange={handleInputChange} placeholder="Booking ID" className="form-input" /></td>
//               <td><input type="number" name="amount" value={newPayment.amount} onChange={handleInputChange} placeholder="Amount" step="0.01" className="form-input" /></td>
//               <td><input type="text" name="status" value={newPayment.status} onChange={handleInputChange} placeholder="Status" className="form-input" /></td>
//               <td></td> {/* Created At auto-generated by backend */}
//               <td>
//                 <button className="save-btn" onClick={handleCreate}><FaEdit /></button>
//                 <button className="cancel-btn" onClick={handleCancel}><FaTrash /></button>
//               </td>
//             </tr>
//           )}
//           {payments.map((payment) => (
//             <tr key={payment.payment_id} className="payment-row">
//               <td>{payment.payment_id}</td>
//               <td>{payment.booking_id}</td>
//               <td>{payment.amount}</td>
//               <td>{payment.status}</td>
//               <td>{payment.created_at}</td>
//             </tr>
//           ))}
//         </tbody>
//       </table>
//     </div>
//   );
// };

// export default ManagePayments;









// src/dashboard/AdminDashboard/ManagePayments/ManagePayments.tsx
import React, { useEffect, useState } from 'react';
import { useAppSelector, useAppDispatch } from '../../../app/store';
import { setLoading, setPayments, setError, createPayment } from '../../../features/payments/paymentSlice';
import { FaEdit } from 'react-icons/fa'; // Already correct
import { FaTrash } from 'react-icons/fa'; // Ensure this import is present
import './ManagePayments.css';

// Define PublicUser interface based on auth.service.ts
interface PublicUser {
  user_id: number;
  email: string | null;
  name: string;
  role: "user" | "admin" | null;
}

// Define Payment interface and export it to avoid "unused" warning
export interface Payment {
  payment_id: number;
  user_id: number;
  booking_id: number;
  amount: number;
  status: string;
  created_at: string;
}

const ManagePayments = () => {
  const { payments, loading, error } = useAppSelector((state) => state.payments);
  const dispatch = useAppDispatch();
  const { token, user } = useAppSelector((state) => state.user) as { token: string | null; user: PublicUser | null };
  const role = user?.role;
  const userId = user?.user_id;

  const [creating, setCreating] = useState(false);
  const [newPayment, setNewPayment] = useState({
    booking_id: '',
    amount: '',
    status: 'pending', // Default status
  });

  useEffect(() => {
    const fetchPayments = async () => {
      if (!userId || !token) return;
      dispatch(setLoading());
      try {
        const url = role === 'admin' ? 'http://localhost:8081/payments' : `http://localhost:8081/payments?userId=${userId}`;
        const response = await fetch(url, {
          headers: { Authorization: `Bearer ${token}` },
        });
        if (!response.ok) {
          throw new Error('Failed to fetch payments');
        }
        const result = await response.json();
        dispatch(setPayments(result));
      } catch (err: unknown) {
        let message = 'Network error occurred';
        if (err instanceof Error) {
          message = err.message;
        }
        dispatch(setError(message));
      }
    };
    fetchPayments();
  }, [dispatch, token, role, userId]);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setNewPayment((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const handleCreate = async () => {
    if (!userId) return;
    const payload = {
      booking_id: parseInt(newPayment.booking_id, 10),
      amount: parseFloat(newPayment.amount),
      status: newPayment.status,
    };
    dispatch(setLoading());
    try {
      const response = await fetch('http://localhost:8081/payments', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify(payload),
      });
      if (!response.ok) throw new Error('Create failed');
      const result = await response.json();
      dispatch(createPayment(result));
      setCreating(false);
      setNewPayment({
        booking_id: '',
        amount: '',
        status: 'pending',
      });
    } catch (err: unknown) {
      let message = 'Network error occurred';
      if (err instanceof Error) {
        message = err.message;
      }
      dispatch(setError(message));
    }
  };

  const handleCancel = () => {
    setCreating(false);
    setNewPayment({
      booking_id: '',
      amount: '',
      status: 'pending',
    });
  };

  if (loading) return <div className="loading">Loading...</div>;
  if (error) return <div className="error-message">{error}</div>;

  return (
    <div className="manage-payments">
      <h2 className="payments-title">Manage Payments</h2>
      <button className="create-btn" onClick={() => setCreating(true)}>Create Payment</button>
      <table className="payments-table">
        <thead>
          <tr>
            <th>Payment ID</th>
            <th>Booking ID</th>
            <th>Amount</th>
            <th>Status</th>
            <th>Created At</th>
          </tr>
        </thead>
        <tbody>
          {creating && (
            <tr className="payment-row">
              <td></td> {/* Payment ID auto-generated by backend */}
              <td><input type="number" name="booking_id" value={newPayment.booking_id} onChange={handleInputChange} placeholder="Booking ID" className="form-input" /></td>
              <td><input type="number" name="amount" value={newPayment.amount} onChange={handleInputChange} placeholder="Amount" step="0.01" className="form-input" /></td>
              <td><input type="text" name="status" value={newPayment.status} onChange={handleInputChange} placeholder="Status" className="form-input" /></td>
              <td></td> {/* Created At auto-generated by backend */}
              <td>
                <button className="save-btn" onClick={handleCreate}><FaEdit /></button>
                <button className="cancel-btn" onClick={handleCancel}><FaTrash /></button>
              </td>
            </tr>
          )}
          {payments.map((payment: Payment) => ( // Explicitly type the parameter
            <tr key={payment.payment_id} className="payment-row">
              <td>{payment.payment_id}</td>
              <td>{payment.booking_id}</td>
              <td>{payment.amount}</td>
              <td>{payment.status}</td>
              <td>{payment.created_at}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default ManagePayments;